### ISSUE TITLE
How to compile without installing system packages

### ISSUE THREAD

**Issue by HuStmpHrrr** [hendriktews/proof-tree#3]
The Install.md only mentioned how to compile from source in debian systems. I'd imagine that it's possible to compile in other systems as well. Specifically, how can I resolve the dependencies via install packages from `opam`?

**Comment by hendriktews** [comment]
> Specifically, how can I resolve the dependencies via install
> packages from opam?

For opam you just need lablgtk.

H.

**Comment by HuStmpHrrr** [comment]
Indeed it worked.
