### ISSUE TITLE
proof tree doesn't seem to play well with coq 8.6

### ISSUE THREAD

**Issue by HuStmpHrrr** [hendriktews/proof-tree#4]
I have the following error when I try to launch prooftree:

```
Coq existential variable info parsing error!
The parser died on the input
  (dependent evars: (printing disabled) )
with an exception Scan_failure with message
expected an evar (starting with '?') or the end of the evar info (a ')'); but found '('
```

```
$ coqc -v
The Coq Proof Assistant, version 8.6 (September 2017)
compiled on Sep 8 2017 13:44:19 with OCaml 4.02.3
```

Is there anyway I can see the concrete input object?

**Comment by HuStmpHrrr** [comment]
Ah, I see, it's a known problem: https://coq.inria.fr/bugs/show_bug.cgi?id=4504

sorry about the noise.

**Comment by hendriktews** [comment]
I believe I fixed the parsing problem in proof-tree. The newest version of proof-tree should not crash with coq 8.6, if it does, please reopen.

**Comment by HuStmpHrrr** [comment]
@hendriktews the error above is from the prooftree i git pull from master branch a moment ago.

```
$ git rev-parse HEAD
e5edcebd6e3398614556e6fbab8b3870e5dc9862
```

**Comment by hendriktews** [comment]
Now I see that your output shows "printing disabled". Proof general should enable evar printing when you switch on proof-tree. What version of ProofGeneral are you using?

**Comment by HuStmpHrrr** [comment]
```
$ git rev-parse HEAD
9083698d0bbd4438208fa72222438ae59684542d
$ git log -1
commit 9083698d0bbd4438208fa72222438ae59684542d
Author: Erik Martin-Dorel <erik@martin-dorel.org>
Date:   Tue Aug 15 11:31:36 2017 +0200

    Fix pg-{show,hide}-all-proofs and Move them into pg-user.el.
    
    This commit address ProofGeneral/PG#193.
```

from PG folder.

It should also be the latest master from the repo. Do you have a working revision such that I can test it on my side?

**Comment by hendriktews** [comment]
I use pretty old a424cf37d41c7d9c7443132a385b89f3947bc708 from Feb 2017. Do you use the new parallel processing feature of PG? Maybe switching this off might help.

**Comment by HuStmpHrrr** [comment]
It turns out that I have a line in my init file setting `coq-prog-name`, i.e.

```
(setq coq-prog-name "...")
```

and it works once I commented out the line, and the coqtop path I specified was exactly the same as the one in PATH. PG itself was fine with the line, however. not sure what happened.

**Comment by hendriktews** [comment]
When you process some piece of a file in PG, it starts coqtop in the background. All the output from that coqtop is in buffer ``*coq*'', the first line shows the version. Could you look in that buffer and send the version with and without that coq-prog-name line active?

**Comment by hendriktews** [comment]
The name of the buffer is `*coq*`

**Comment by HuStmpHrrr** [comment]
without:

```
Welcome to Coq 8.6 (September 2017)      
                                         
```

`C-h v coq-prog-name`:

```
coq-prog-name is a variable defined in `coq-system.el'.
Its value is "coqtop"                                  
                                                       
```

with:
```
Welcome to Coq 8.6 (September 2017)   
                                      
```

`C-h v coq-prog-name`:

```
coq-prog-name is a variable defined in `coq-system.el'.  
Its value is "~/Tools/opam-coq.8.6/4.02.3/bin/coqtop"    
Original value was "coqtop"                              
                                                         
```

it's worth to mention `coqtop` eventually goes to the same path(via symlink).

**Comment by hendriktews** [comment]
Thanks. I have to try this, it should also work with the coq-prog-name setting.
